version: "3.2"

services:
  meu-monguinho:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - my-proxy-net
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - meu-monguinho
    networks:
      - my-proxy-net
      
networks:
  my-proxy-net:
    external:
      name: custom_network


volumes:
  mongodb_data_container:
  